CREATE DATABASE QUANLYCAFE
GO
USE QUANLYCAFE
GO

CREATE TABLE NHANVIEN
(
	ID INT IDENTITY(1,1),
	MANV VARCHAR(10) PRIMARY KEY NOT NULL,
	TENNV NVARCHAR(30) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	NGAYSINH DATETIME NOT NULL CHECK (YEAR(GETDATE())-YEAR(NGAYSINH)>=16),
	SDT VARCHAR(10) NOT NULL UNIQUE,
	TAIKHOAN VARCHAR(20) NOT NULL UNIQUE,
	MATKHAU VARCHAR(20) NOT NULL DEFAULT 12345,
	CHUCVU NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
)
INSERT INTO NHANVIEN(MANV,TENNV,GIOITINH,NGAYSINH,SDT,TAIKHOAN,CHUCVU,DIACHI) VALUES('18004112',N'Nguyễn Phát Tài','Nam','1/6/2000','0392923693','tainguyen',N'Quản lý','Vĩnh Long')
GO
CREATE TABLE KHACHHANG
(
	ID INT IDENTITY(1,1),
	MAKH VARCHAR(10) PRIMARY KEY NOT NULL,
	TENKH NVARCHAR(30) NOT NULL,
	SDT VARCHAR(10) NOT NULL UNIQUE,
	DTL INT DEFAULT 0,
)
GO
CREATE TABLE LOAIMON
(
	ID INT IDENTITY(1,1),
	MALOAI VARCHAR(10) PRIMARY KEY NOT NULL,
	TENLOAI NVARCHAR(30) NOT NULL UNIQUE,
)
GO
CREATE TABLE MON
(
	ID INT IDENTITY(1,1),
	MAMON VARCHAR(10) PRIMARY KEY NOT NULL,
	TENMON NVARCHAR(30) NOT NULL UNIQUE,
	MALOAI VARCHAR(10) NOT NULL,
	DONGIA BIGINT NOT NULL,
	FOREIGN KEY(MALOAI) REFERENCES LOAIMON(MALOAI),
)
GO

CREATE TABLE HOADON
(
	ID INT IDENTITY(1,1),
	MAHD VARCHAR(10) PRIMARY KEY NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	MAKH VARCHAR(10),
	SOBAN INT,
	NGAYBAN DATETIME NOT NULL,
	GIAMGIA BIGINT,
	TONGTIEN BIGINT,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
)
GO
CREATE TABLE CTHD
(
	MAHD VARCHAR(10) NOT NULL,
	MAMON VARCHAR(10) NOT NULL,
	SL INT NOT NULL,
	DONGIA BIGINT,
	THANHTIEN BIGINT,
	FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY (MAMON) REFERENCES MON(MAMON),
)
GO
CREATE TABLE SANPHAM
(
	ID INT IDENTITY(1,1),
	MASP VARCHAR(10) PRIMARY KEY NOT NULL,
	TENSP NVARCHAR(30) NOT NULL UNIQUE,
	DVT NVARCHAR(30) NOT NULL,
	SL INT DEFAULT 0,
)
GO
CREATE TABLE PHIEUNHAP
(
	ID INT IDENTITY(1,1),
	MAPN VARCHAR(10) PRIMARY KEY NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	NGAYNHAP DATETIME NOT NULL,
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
)
GO
CREATE TABLE CTPN
(
	MAPN VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,	
	SL INT NOT NULL,
	DONGIA BIGINT,
	THANHTIEN BIGINT,
	FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN),
	FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
)
GO
CREATE TABLE PHIEUXUAT
(
	ID INT IDENTITY(1,1),
	MAPX VARCHAR(10) PRIMARY KEY NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	NGAYXUAT DATETIME NOT NULL,
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
)
GO
CREATE TABLE CTPX
(
	MAPX VARCHAR(10) NOT NULL,
	MASP VARCHAR(10) NOT NULL,
	SL INT NOT NULL,
	FOREIGN KEY(MAPX) REFERENCES PHIEUXUAT(MAPX),
	FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
)

GO
CREATE TABLE CHAMCONG
(
	ID INT IDENTITY(1,1),
	MACC VARCHAR(10) PRIMARY KEY NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	NGAYCC DATETIME,
)
GO
CREATE TABLE CTCC
(
	MACC VARCHAR(10) NOT NULL,
	MANV VARCHAR(10) NOT NULL,
	LUONGTHEONGAY BIGINT NOT NULL,
	SONGAYLAM INT NOT NULL DEFAULT 0,
	SONGAYNGHI INT NOT NULL DEFAULT 0,
	TAMUNG BIGINT NOT NULL DEFAULT 0,
	THUONG BIGINT NOT NULL DEFAULT 0,
	PHAT BIGINT NOT NULL DEFAULT 0,
	GHICHU VARCHAR(500),
	THUCLANH BIGINT,
	FOREIGN KEY(MACC) REFERENCES CHAMCONG(MACC),
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
)
GO

--TRIGGER PN
GO
CREATE TRIGGER IS_PHIEUNHAP
ON CTPN
FOR INSERT
AS
BEGIN
	UPDATE SANPHAM SET SANPHAM.SL = SANPHAM.SL + inserted.SL FROM inserted, SANPHAM WHERE SANPHAM.MASP = inserted.MASP
END
GO

CREATE TRIGGER DL_PHIEUNHAP
ON CTPN
FOR DELETE
AS
BEGIN
	UPDATE SANPHAM SET SANPHAM.SL = SANPHAM.SL - deleted.SL FROM deleted, SANPHAM WHERE SANPHAM.MASP = deleted.MASP
END
GO

--TRIGGER PX
CREATE TRIGGER IS_PHIEUXUAT
ON CTPX
FOR INSERT
AS
BEGIN
	DECLARE @SLT INT;
	DECLARE @SL INT
	SELECT @SLT = SANPHAM.SL FROM SANPHAM, inserted WHERE SANPHAM.MASP = inserted.MASP
	SELECT @SL = inserted.SL FROM inserted,SANPHAM WHERE SANPHAM.MASP = inserted.MASP
	IF @SLT <@SL
		BEGIN
			RAISERROR(N'EROR',16,1)
			ROLLBACK TRANSACTION
		END
	ELSE
		BEGIN
			UPDATE SANPHAM SET SANPHAM.SL = SANPHAM.SL - inserted.SL FROM inserted, SANPHAM WHERE SANPHAM.MASP = inserted.MASP
		END
END
GO

CREATE TRIGGER DL_PHIEUXUAT
ON CTPX
FOR DELETE
AS
BEGIN
	UPDATE SANPHAM SET SANPHAM.SL = SANPHAM.SL + deleted.SL FROM deleted, SANPHAM WHERE SANPHAM.MASP = deleted.MASP
END
GO

CREATE PROCEDURE BAOCAODOANHTHU(@NGAYBATDAU DATETIME,@DENNGAY DATETIME)
AS
DECLARE @STAR DATETIME = @NGAYBATDAU
DECLARE @END DATETIME = @DENNGAY
SELECT HOADON.MANV+' - '+TENNV AS N'Nhân viên lập phiếu' ,CTHD.MAHD AS N'Mã hóa đơn', NGAYBAN AS N'Ngày bán',SUM(THANHTIEN) AS N'Doanh thu', @STAR AS N'Từ ngày',@END AS N'Đến ngày'
FROM CTHD,NHANVIEN,HOADON WHERE HOADON.MANV = NHANVIEN.MANV AND HOADON.MAHD = CTHD.MAHD AND NGAYBAN BETWEEN @NGAYBATDAU AND @DENNGAY 
GROUP BY CTHD.MAHD , NGAYBAN ,HOADON.MANV, NHANVIEN.TENNV
GO

CREATE PROCEDURE BAOCAOCHAMCONG(@MACC VARCHAR(10),@NGUOICHAMCONG NVARCHAR(30))
AS
DECLARE @NCC NVARCHAR(30) = @NGUOICHAMCONG
SELECT @NCC AS N'Người chấm công',CHAMCONG.MACC AS N'Phiếu chấm công',CTCC.MANV+' - '+TENNV AS N'Nhân viên',LUONGTHEONGAY AS N'Lương theo ngày', SONGAYLAM AS N'Số ngày làm', 
SONGAYLAM AS N'Số ngày nghỉ',THUONG AS N'Thưởng', PHAT AS N'Phạt',TAMUNG AS N'Tạm ứng',THUCLANH AS N'Thực lãng',GHICHU AS N'Ghi chú'
FROM CHAMCONG,CTCC,NHANVIEN
WHERE CHAMCONG.MACC=CTCC.MACC AND NHANVIEN.MANV=CTCC.MANV AND CHAMCONG.MACC=@MACC

SELECT * FROM HOADON
SELECT * FROM KHACHHANG
UPDATE KHACHHANG SET DTL = 40 WHERE MAKH='KH1'
UPDATE KHACHHANG SET DTL = 100 WHERE MAKH='KH2'
UPDATE KHACHHANG SET DTL = 150 WHERE MAKH='KH3'

select * from HOADON
BAOCAODOANHTHU '2/5/2000','5/24/2021'

SELECT * FROM CTHD,HOADON,MON,NHANVIEN WHERE HOADON.MAHD='HD15' AND MON.MAMON=CTHD.MAMON AND NHANVIEN.MANV=HOADON.MANV AND CTHD.MAHD=HOADON.MAHD

select * from CTHD where MAHD = 'HD15'